"""Add YouTubePlaylist model

Revision ID: 5a64284a51c3
Revises: d734b3397f2c
Create Date: 2025-03-27 20:48:40.973257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a64284a51c3'
down_revision = 'd734b3397f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('you_tube_playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('playlist_id', sa.String(length=100), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=200), nullable=True),
    sa.Column('is_playlist', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('you_tube_playlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_you_tube_playlist_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('uploaded_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['uploaded_by'], ['id'])
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('duration')
        batch_op.drop_column('cover_image')

    with op.batch_alter_table('you_tube_playlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_you_tube_playlist_timestamp'))

    op.drop_table('you_tube_playlist')
    # ### end Alembic commands ###
